name: Lint Commit Message
concurrency:
  group: ci-${{ github.ref }}-commitlint
  cancel-in-progress: true

on:
  pull_request:
    types: [edited, synchronize, opened, reopened]
    branches:
      - main

jobs:
  lint-commit-message:
    name: Run commitlint
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install dependencies
        # If we don't do this, commitlint throws errors about
        # not finding rules package for commit message conventions
        run: npm ci
      - name: Validate PR commits with commitlint
        # Using env below rather than accessing them
        # directly due to GitHub Docs recommendation
        # that this is better for security as it
        # mitigates script injection attacks :
        # https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable
        env:
          prtitle: ${{ github.event.pull_request.title }}
          prdescription: ${{ github.event.pull_request.body }}
        run: printf "$prtitle\n\n$prdescription" | npx commitlint
